name        = "fortran-regex"
author      = "Federico Perini"
copyright   = "Copyright (c) 2022-2023, Federico Perini" 
version     = "1.1.0"
license     = "MIT"
description = "Fortran regex library"
homepage    = "https://github.com/perazz/fortran-regex"
keywords    = ["regex","regular expressions","strings"]

[build]
auto-executables = false
auto-examples    = false
auto-tests       = true

[library]
source-dir  = "src"
include-dir = "src"

[install]
library = true

[[test]]
name="regex_tests"
source-dir="test"
main="tests.f90"

